# Generated by Django 3.2.17 on 2023-06-20 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DpartmentTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpartement_name', models.CharField(max_length=20, null=True)),
                ('op_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=10)),
                ('user_mail', models.CharField(max_length=100, null=True)),
                ('user_phone', models.CharField(max_length=20, null=True)),
                ('user_stat', models.CharField(max_length=1)),
                ('user_type', models.CharField(max_length=1)),
                ('stu_num', models.CharField(max_length=2, null=True)),
                ('remark', models.CharField(max_length=500, null=True)),
                ('op_no', models.CharField(max_length=20)),
                ('op_time', models.DateTimeField(auto_now_add=True)),
                ('dpartment_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.dpartmenttable')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=100)),
                ('teacher_no', models.CharField(max_length=20)),
                ('part_in_no', models.CharField(max_length=10)),
                ('sub_viscera', models.CharField(max_length=1000)),
                ('postil_flag', models.CharField(max_length=1, null=True)),
                ('postil', models.CharField(max_length=200, null=True)),
                ('year', models.CharField(max_length=4)),
                ('op_no', models.CharField(max_length=20)),
                ('op_time', models.DateTimeField(auto_now_add=True)),
                ('dpartment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.dpartmenttable')),
            ],
        ),
        migrations.CreateModel(
            name='SelectSubTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_no', models.CharField(max_length=20)),
                ('sub_no', models.CharField(max_length=20)),
                ('stu_no', models.CharField(max_length=20)),
                ('postil_flag', models.CharField(max_length=1, null=True)),
                ('postil', models.CharField(max_length=200, null=True)),
                ('year', models.CharField(max_length=4)),
                ('wish_flag', models.CharField(max_length=1)),
                ('wish', models.CharField(max_length=200, null=True)),
                ('op_no', models.CharField(max_length=20)),
                ('op_time', models.DateTimeField(auto_now_add=True)),
                ('dpartment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.dpartmenttable')),
            ],
        ),
    ]
